import React, { useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const BACKEND = import.meta.env.VITE_BACKEND_URL;

interface RFQMarkdownProps {
    content: string;
}

export const RFQMarkdown: React.FC<RFQMarkdownProps> = ({ content }) => {
    const processedText = useMemo(() => {
        let text = content || "";

        // Stage 0: Strip redundant labels generated by AI (e.g., **CRITICAL - ATTACHED IMAGE:**)
        text = text.replace(/(\*\*)?CRITICAL\s*-\s*ATTACHED\s*IMAGE:?(\*\*)?/gi, '');
        text = text.replace(/(\*\*)?ATTACHED\s*IMAGE:?(\*\*)?/gi, '');

        // Stage 0.1: Strip bold/underline wrappers from image tags (e.g., **[[IMAGE_ID:n]]**)
        text = text.replace(/(\*\*|__)?\[\[IMAGE_ID:(\d+)\]\](\*\*|__)?/g, '[[IMAGE_ID:$2]]');

        // Stage 1: Replace [[IMAGE_ID:n]] in markdown targets
        text = text.replace(/\(\[\[IMAGE_ID:(\d+)\]\]\)/g, `(${BACKEND}/images/$1)`);

        // Stage 2: Replace stand-alone [[IMAGE_ID:n]] tags with Deduplication
        const seenIds = new Set<string>();
        text = text.replace(/\[\[IMAGE_ID:(\d+)\]\]/g, (match, id) => {
            if (seenIds.has(id)) {
                return ''; // Remove duplicate occurrence
            }
            seenIds.add(id);
            return `\n\n![VISION COMPONENT: ID ${id}](${BACKEND}/images/${id})\n\n`;
        });

        // Stage 3: Filter out unwanted TOC entries and process lines
        const lines = text.split('\n');
        const transformedLines = lines
            .filter(line => {
                const trimmed = line.trim();
                // Remove "14. References & Standards" from table of contents
                if (/^14\.\s+References\s+(&|and)\s+Standards/i.test(trimmed)) {
                    return false;
                }
                return true;
            })
            .map(line => {
                const trimmed = line.trim();

                const cleanLine = trimmed.replace(/^\*\*|\*\*$/g, '').trim();

                // Only promote real major Section Headers (e.g., "1. SCOPE", "Section 1:")
                // These must be Uppercase and usually have a number followed by a period or colon.
                const isNumberedSection = /^(\d+\.|\d+\.\d+|Section\s+\d+:)\s+[A-Z\s&]{3,}/.test(cleanLine);
                const isUpperCase = cleanLine === cleanLine.toUpperCase();
                const hasStandardFormat = cleanLine.includes(':') && !cleanLine.startsWith('Section');

                // Major Numbered Section -> ##
                if (isNumberedSection && isUpperCase && !hasStandardFormat && cleanLine.length < 60) {
                    return `## ${cleanLine}`;
                }

                // Unnumbered Major Titles (e.g. "Document Overview", "Technical Requirements") -> ##
                // These should be large and blue like Numbered Sections.
                const isLikelySubHeader = /^[A-Z][A-Za-z\s&]{3,30}$/.test(cleanLine);
                if (isLikelySubHeader && !cleanLine.includes('.') && !isUpperCase) {
                    return `## ${cleanLine.toUpperCase()}`;
                }

                return line;
            });

        return transformedLines.join('\n');
    }, [content]);

    return (
        <div className="prose prose-slate prose-sm md:prose-base !prose-headings:text-slate-900 !prose-p:text-slate-600 prose-img:rounded-xl prose-img:shadow-lg max-w-none">
            <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                    h1: ({ node, ...props }) => (
                        <h1 className="text-3xl font-black text-[#006680] mb-8 border-b-4 pb-4 border-slate-200 uppercase tracking-tighter" {...props} />
                    ),
                    h2: ({ node, ...props }) => (
                        <h2 className="text-2xl font-extrabold text-[#006680] mt-12 mb-6 border-b-2 pb-2 border-slate-200 uppercase tracking-tight" {...props} />
                    ),
                    h3: ({ node, ...props }) => (
                        <h3 className="text-lg font-bold text-slate-800 mt-6 mb-2 flex items-center gap-2" {...props} />
                    ),
                    p: ({ node, ...props }) => (
                        <p className="mb-6 leading-relaxed whitespace-pre-wrap text-slate-800 font-sans text-base" {...props} />
                    ),
                    ul: ({ node, ...props }) => (
                        <ul className="list-disc pl-6 mb-8 space-y-3" {...props} />
                    ),
                    ol: ({ node, ...props }) => (
                        <ol className="list-decimal pl-6 mb-8 space-y-3" {...props} />
                    ),
                    li: ({ node, ...props }) => (
                        <li className="text-slate-800 font-sans text-base marker:text-[#006680] marker:font-bold" {...props} />
                    ),
                    strong: ({ node, ...props }) => (
                        <strong className="font-bold text-[#006680]" {...props} />
                    ),
                    table: ({ node, ...props }) => (
                        <div className="my-8 w-full overflow-hidden rounded-xl border border-slate-200 shadow-sm">
                            <table className="w-full text-left text-sm" {...props} />
                        </div>
                    ),
                    thead: ({ node, ...props }) => <thead className="bg-slate-50 text-slate-500 uppercase text-[11px] font-bold tracking-wider" {...props} />,
                    th: ({ node, ...props }) => <th className="px-6 py-4 border-b border-slate-200" {...props} />,
                    td: ({ node, ...props }) => <td className="px-6 py-4 border-b border-slate-100 last:border-0" {...props} />,
                    img: ({ node, ...props }) => (
                        <div className="my-10 flex flex-col items-center">
                            <img
                                {...props}
                                className="max-h-[500px] w-full object-contain rounded-2xl shadow-xl border border-slate-200"
                                onError={(e) => {
                                    console.error("❌ Image failed to load:", props.src);
                                    e.currentTarget.style.display = 'none';
                                    const fallback = document.createElement('div');
                                    fallback.className = "p-4 border-2 border-dashed border-red-200 rounded-xl bg-red-50 text-red-500 text-xs text-center";
                                    fallback.innerText = `Image Failed to Load (ID: ${props.src?.split('/').pop()})`;
                                    e.currentTarget.parentElement?.appendChild(fallback);
                                }}
                            />
                            <span className="mt-4 text-[10px] uppercase tracking-[0.2em] text-slate-500 font-black bg-slate-100 px-4 py-1.5 rounded-full border border-slate-200 shadow-sm">
                                {props.alt || "Vision Component Illustration"}
                            </span>
                        </div>
                    )
                }}
            >
                {processedText}
            </ReactMarkdown>
        </div>
    );
};
