from typing import List

def generate_rfq(prompt: str, refs: List[dict]) -> str:
    """
    Generates RFQ draft using retrieved reference chunks
    """

    if not refs or len(refs) == 0:
        ref_text = "No relevant RFQ reference documents were found."
    else:
        ref_text = "\n\n".join([
            f"[SOURCE: {r['source']['file']}#chunk{r['source'].get('chunk_id', 0)}]\n{r['text']}"
            for r in refs
        ])

    draft = f"""
================ RFQ GENERATED DRAFT ================

USER REQUIREMENT
----------------
{prompt}

REFERENCE RFQ CONTEXT
----------------------
{ref_text}

RFQ SUMMARY
------------
This RFQ has been generated by analyzing the user's requirement 
and matching it against historical RFQ documents to extract relevant 
technical and procurement context. Suppliers are expected to provide:

1️⃣ Pricing details  
2️⃣ Delivery schedule  
3️⃣ Technical compliance  
4️⃣ Warranty & Support conditions  
5️⃣ Commercial terms

=====================================================
"""
    return draft.strip()
